name: Test Document Processor

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/document-processing/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Format code
        run: |
          pip install black
          black --check .

      - name: Run tests
        run: |
          pip install pytest
          pytest tests/

      - name: Report coverage
        run: |
          pip install coverage
          coverage run -m pytest tests/
          coverage report
          coverage xml