name: Claims Processor CI/CD

env:
  PYTHON_VERSION: '3.11'
  POSTGRES_DB: claims_test_db
  POSTGRES_USER: claimsuser
  POSTGRES_PASSWORD: Claims2024#Secure!
  AWS_REGION: ap-south-1

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, develop ]

jobs:
  security-scan:
    name: Security Analysis
    runs-on: ubuntu-latest
    outputs:
      scan_status: ${{ steps.process_scan.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          
      - name: Run security scans
        id: security_scan
        run: |
          mkdir -p reports/security
          bandit -r src/ -f json -o reports/security/bandit.json || true
          safety check -r requirements.txt --json > reports/security/safety.json || true
          
      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: reports/security/
          retention-days: 14

      - name: Process scan results
        id: process_scan
        if: always()
        run: |
          if [ -f reports/security/bandit.json ] && [ -f reports/security/safety.json ]; then
            echo "status=✅ Success" >> $GITHUB_OUTPUT
            echo "Security scans completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "status=⚠️ Warning" >> $GITHUB_OUTPUT
            echo "Security scans partially completed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Notify Google Chat
        if: always()
        run: |
          MESSAGE=$(cat << EOF
          *Security Scan Results*
          Status: ${{ steps.process_scan.outputs.status }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
          )
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"$MESSAGE\"}" \
            "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"

  validate:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort mypy pylint
          pip install -r requirements-dev.txt
          
      - name: Check formatting
        run: |
          black --check src/ tests/ --diff --color > reports/black.txt || echo "Black formatting issues found"
          isort --check-only src/ tests/ --diff --color > reports/isort.txt || echo "Import sorting issues found"
          
      - name: Run type checking
        run: |
          mypy src/ tests/ --ignore-missing-imports --html-report reports/mypy --txt-report reports/mypy.txt --verbosity 0

      - name: Run pylint
        run: |
          pylint src/ tests/ --output-format=parseable:reports/pylint.txt,json:reports/pylint.json

      - name: Upload code quality reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            reports/black.txt
            reports/isort.txt
            reports/mypy.txt
            reports/mypy/
            reports/pylint.txt
            reports/pylint.json

      - name: Notify Google Chat on Validation Completion
        if: always()
        run: |
          STATUS=":x: Failure"
          if [[ "${{ job.status }}" == "success" ]]; then
            STATUS=":white_check_mark: Success"
          fi
          
          MESSAGE=$(cat <<EOF
          {
            "text": "*Code Quality Check Completed*\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nStatus: ${STATUS}\nDetails: [View on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }
EOF
          )
          
          curl -X POST -H "Content-Type: application/json" -d "${MESSAGE}" "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"

  test:
    name: Test
    needs: [security-scan, validate]
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          
      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@localhost:5432/${{ env.POSTGRES_DB }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          python -m pytest tests/ \
            -v \
            --asyncio-mode=auto \
            --cov=src \
            --cov-report=xml \
            --cov-report=html \
            --junit-xml=reports/junit.xml
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            reports/
            coverage.xml
            htmlcov/
            reports/junit.xml

      - name: Notify Google Chat on Test Completion
        if: always()
        run: |
          STATUS=":x: Failure"
          if [[ "${{ job.status }}" == "success" ]]; then
            STATUS=":white_check_mark: Success"
          fi
          
          MESSAGE=$(cat <<EOF
          {
            "text": "*Testing Completed*\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nStatus: ${STATUS}\nDetails: [View on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }
EOF
          )
          
          curl -X POST -H "Content-Type: application/json" -d "${MESSAGE}" "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"

  build:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/claims-processor:${{ github.sha }}
            ${{ secrets.DOCKER_REGISTRY }}/claims-processor:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/claims-processor:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/claims-processor:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Notify Google Chat on Build Completion
        if: always()
        run: |
          STATUS=":x: Failure"
          if [[ "${{ job.status }}" == "success" ]]; then
            STATUS=":white_check_mark: Success"
            IMAGE_INFO="\nImage: ${{ secrets.DOCKER_REGISTRY }}/claims-processor:${{ github.sha }}"
          else
            IMAGE_INFO=""
          fi
          
          MESSAGE=$(cat <<EOF
          {
